export const fullNavList = [
    {module: 'app',   level: 0,   text: 'HomePage',      icon: 'home',          link: 'homepage'},
    {module: 'app',   level: 50,  text: 'Bulletins',     icon: 'event_note',    link: 'app-tenant/bulletins'},
    {module: 'store', level: 0,   text: 'Winkel',        icon: 'store',         link: 'store-user/store'},
    {module: 'store', level: 50,  text: 'Orders',        icon: 'list',          link: 'store-tenant/orders'},
    {module: 'store', level: 50,  text: 'Orderregels',   icon: 'view_list',     link: 'store-tenant/orderlines'},
    {module: 'app',   level: 50,  text: 'Settings',      icon: 'settings',      link: 'app-tenant/settings'},
    {module: 'app',   level: 100, text: 'Tenants',       icon: 'store',         link: 'app-super/tenants'},
    {module: 'app',   level: 50,  text: 'Organisaties',  icon: 'business',      link: 'app-tenant/organisations'},
    {module: 'app',   level: 50,  text: 'Medewerkers',   icon: 'person',        link: 'app-tenant/employees'},
    {module: 'store', level: 50,  text: 'Categorieën',   icon: 'more',          link: 'store-tenant/categories'},
    {module: 'app',   level: 50,  text: 'Kenmerken',     icon: 'class',         link: 'app-tenant/properties'},
    {module: 'store', level: 50,  text: 'Artikelen',     icon: 'label_outline', link: 'store-tenant/articles'},
    {module: 'app',   level: 50,  text: 'Afbeeldingen',  icon: 'image',         link: 'app-tenant/images'},
  ]
